import React, {Component} from 'react';

class HomePage extends Component {
  render() {
    return (
      <div className="">
        <h3>API Platform - generate crud - demo app</h3>
        <div>
          <ul>
            <li>React front app demo for&nbsp;
              <a href="https://api-platform.com/">API Platform</a>
            </li>
            <li>
              React components generated by&nbsp;
              <a href="https://github.com/mysiar/generate-crud">
                generate-crud
              </a>
            </li>
          </ul>
        </div>
      </div>
    );
  }
}

export default HomePage;
