import React, {Component} from 'react';

class HomePage extends Component {
  render() {
    return (
<<<<<<< HEAD
      <div className="container">
=======
      <div>
>>>>>>> 254f801ec10824fe092c85fd44e24c922cd1f0a6
        <h3>API Platform - generate crud - demo app</h3>
        <div>
          <ul>
            <li>
              <a href="https://github.com/mysiar/api-platofrm-genereate-crud-demo-app">GitHub</a>
            </li>
            <li>React front app demo for&nbsp;
              <a href="https://api-platform.com/">API Platform</a>
            </li>
            <li>
              React components generated by&nbsp;
              <a href="https://github.com/mysiar/generate-crud">
                generate-crud
              </a>
            </li>
          </ul>
        </div>
      </div>
    );
  }
}

export default HomePage;
